INSERT INTO "Product" ("Name", "Price", "Quantity", "Description")
VALUES
	('Smarthpone', 249.99, 10, 'High-end smartphone with a powerful processor and advanced camera system.'),
	('Laptop', 459.99, 7, 'Ultrabook with long battery life and high-resolution display.'),
	('Headphones', 19.99, 20, 'Noise-cancelling over-ear headphones with superior sound quality.'),
	('Smartwatch', 79.89, 8, 'Fitness and health tracking smartwatch.'),
	('Tablet', 124.99, 5, 'Lightweight tablet with a stylus for drawing and note-taking.'),
	('T-Shirt', 8.99, 18, 'Made from organic cotton with unique design.'),
	('Jeans', 17.69, 16, 'Slim-fit jeans with stretchable fabric for comfort.'),
	('Sneakers', 29.99, 22, 'Stylish and comfortable sneakers suitable for both casual and athletic wear.'),
	('Jacket', 34.49, 12, 'Waterproof jacket for outdoor activities.'),
	('Dress', 22.19, 17, 'Elegant cocktail dress for formal occasions.'),
	('Cereal', 3.89, 30, 'A blend of oats, nuts, and dried fruits, perfect for breakfast or snacks.'),
	('Chocolate', 2.79, 25, 'Dark chocolate bar.'),
	('Pizza', 4.79, 35, 'Classic pepperoni pizza with a crispy crust and gooey cheese.'),
	('Cookies', 3.89, 50, 'Traditional homemade-style chocolate chip cookies.'),
	('Lasagna', 4.59, 24, 'Layers of pasta, meat sauce, and cheese baked to perfection.'),
	('Coffee', 2.99, 31, 'Ready-to-drink cold brew coffee'),
	('Tea', 3.19, 34, 'Organic herbal tea blend for relaxation.'),
	('Energy Drink', 3.59, 40, 'Natural energy drink with caffeine from green tea extract.'),
	('Sparkling Water', 1.89, 44, 'Flavored sparkling water with no added sugars.'),
	('Building Blocks', 5.69, 14, 'Interlocking building blocks for creative construction play.'),
	('RC Car', 19.49, 10, 'High-speed RC car with advanced controls.'),
	('Puzzles', 8.79, 14, 'Jigsaw puzzles with varying difficulty levels and beautiful artwork.'),
	('Cordless Drill', 27.39, 14, 'Powerful and versatile cordless drill for home improvement projects.'),
	('Multi-Tool', 8.89, 30, 'Compact multi-tool with pliers, knife, screwdriver, and more.'),
	('Socket Set', 13.99, 23, 'Comprehensive socket set for automotive and mechanical repairs.'),
	('Hammer', 8.89, 10, 'Heavy-duty claw hammer for construction and DIY tasks.'),
	('Measuring Tape', 3.59, 18, 'Durable measuring tape with easy-to-read markings.'),
	('Lipstick', 5.79, 20, 'Moisturizing lipstick available in a variety of shades.'),
	('Nail Polish', 4.89, 23, 'Quick-drying nail polish'),
	('Hair Gel', 3.49, 40, 'Strong-hold hair gel to style and keep hair in place.'),
	('Shower Gel', 2.89, 37, 'A refreshing and moisturizing shower gel.');